_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 3
                - 8
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.6
            "8":
                - 1
                - 3
                - 5
            "10":
                - 9
                - 17
            "12": 0.19.6
            "13": windows-amd64
activation:
    value: relu
augmentation:
    value: true
dropout_rate:
    value: 0.2
epochs:
    value: 25
image_resize:
    value: 256
loss:
    value: mse
metric:
    value: mae
nb_layers:
    value: 3
nb_neurons:
    value: 128
optimizer:
    value: adam
